apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: config/upstream
  contents:
  - path: .
    git:
      url: https://github.com/isaaguilar/terraform-operator
      ref: origin/master
    newRootPath: deploy/bundles/v0.9.0-beta1